THRESHOLD_SCORE : float = 0.70
AVERGE_CUP_HEIGHT : int = 197
CUP_ERROR_TOLERANCE_PERCENTAGE : int = 15
THRESHOLD_SMALL_CUP_HEIGHT : int = 140
THRESHOLD_MEDIUM_CUP_HEIGHT : int = 185
THRESHOLD_BIG_CUP_HEIGHT : int = 275
UNKNOWN_CLASS : str = "Unknown"
YOLOV8_WINDOW_NAME : str = "Yolov8"
