version: "3.8"

services:
  classifier:
    image: coffee-recommender-model:latest
    ports:
      - "8001:8000" 
  
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: Questionnaires
    ports:
      - "5433:5432"
    networks:
      - questionnaire-llm-updater-network

  mqtt-subscriber:
    image: questionnaire-llm-updater:latest
    networks:
      - questionnaire-llm-updater-network

  spark:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8010:8010'
    volumes:
      - "./cup_detection/messaging/:/opt/spark"
    depends_on:
      - mqtt-subscriber

  spark-worker:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - mqtt-subscriber

networks:
  questionnaire-llm-updater-network:
    driver: bridge