from typing import Dict

params_dict : Dict[str, int] = {
    "BATCH_SIZE" : 128,
    "LEARNING_RATE" : 0.1,
    "EPOCHS" : 10000,
    "GRADIENT_CLIPPING_VALUE" : 0.5,
    "WEIGHT_DECAY" : 0.001,
    "DROPOUT_PROBABILITY_LAYER1" : 0.4,
    "DROPOUT_PROBABILITY_LAYER2" : 0.6,
    "DROPOUT_PROBABILITY_LAYER3" : 0.5, 
    "DROPOUT_PROBABILITY_LAYER4" : 0.6,
    "DROPOUT_PROBABILITY_LAYER5" : 0.4 
}